(lang dune 3.4)

(name "Ocamulator")

(source (github "Sayeem2004/Ocamulator"))

(authors "Mohammad Khan" "Pablo Raigoza" "Evan Vera")

(license MIT)

(package
 (name "Ocamulator")
 (synopsis "This package simulates and executes NES ROMs")
 (depends ocaml dune)
 (allow_empty))
